# Generated by Django 5.1.15 on 2026-10-06 09:05

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('prescriptions', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('shipping_address_snapshot', models.TextField(help_text='Immutable snapshot of shipping address at checkout')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('grand_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('COD', 'Cash on Delivery'), ('ONLINE', 'Card / Digital Payment')], default='COD', max_length=30)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Payment Pending'), ('PROCESSING', 'Processing'), ('PAID', 'Paid'), ('FAILED', 'Payment Failed'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=30)),
                ('order_status', models.CharField(choices=[('PENDING', 'Pending Confirmation'), ('PRESCRIPTION_REVIEW', 'Awaiting Prescription Review'), ('CONFIRMED', 'Confirmed'), ('PROCESSING', 'Processing & Packaging'), ('PACKED', 'Packed & Ready'), ('READY_FOR_PICKUP', 'Ready for Dispatch'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded')], db_index=True, default='PENDING', max_length=30)),
                ('requires_prescription', models.BooleanField(db_index=True, default=False)),
                ('customer_notes', models.TextField(blank=True)),
                ('staff_notes', models.TextField(blank=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('prescription', models.ForeignKey(blank=True, help_text='Attached prescription required for verification', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='prescriptions.prescription')),
                ('shipping_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.address')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name_snapshot', models.CharField(max_length=200)),
                ('sku_snapshot', models.CharField(max_length=60)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prescription_required', models.BooleanField(default=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='products.product')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
