# Generated by Django 5.1.15 on 2026-10-06 09:05

import apps.prescriptions.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prescription_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('uploaded_file', models.FileField(upload_to=apps.prescriptions.models.prescription_upload_path)),
                ('doctor_name', models.CharField(blank=True, max_length=150)),
                ('clinic_hospital', models.CharField(blank=True, max_length=200)),
                ('patient_name', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('UNDER_REVIEW', 'Under Pharmacist Review'), ('APPROVED', 'Approved by Pharmacist'), ('REJECTED', 'Rejected / Invalid'), ('EXPIRED', 'Prescription Expired')], db_index=True, default='PENDING', max_length=30)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_prescriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
